* Option 1: stepped fence
This option would recreate what you have currently: we'd get some more attractive prefabricated fence panels and replace the ones you currently have installed.

** Labor
$400

** Materials
*** Option 1: Pressure treated pine
This is similar to what you have installed currently, but looks a little nicer in my opinion.
**** Product link
https://www.homedepot.com/p/Outdoor-Essentials-6-ft-H-x-8-ft-W-Pressure-Treated-Pine-Dog-Ear-Fence-Panel-158083/203733689
**** Materials breakdown
- 7 fence panels: $510.79, $40.86 sales tax, $552 total
- Fasteners: $10, $0.80 sales tax, 10.80 total
**** Total cost
- Total materials cost: $562.80
- Materials + labor: $962.80

*** Option 2: Stockade fence
I think this is what you currently have installed.
**** Product link
https://www.homedepot.com/p/Barrette-6-ft-H-x-8-ft-W-Flat-Rough-Sawn-Stockade-Privacy-Fence-Panel-73000470/202090100
**** Materials breakdown
- 7 fence panels: $384.79, $30.78 sales tax, $416 total
- Fasteners: $10, $0.80 sales tax, 10.80 total
**** Total cost
- Total materials cost: $426.80
- Materials + labor: $826.80

* Option 2: raked fence
This option would be to install a custom fence which follows the incline of the landscape. There would be a more consistent gap between fencing sections.

** Labor
$800

** Materials
*** Option 1 : Cedar
This would match the rest of your fence around the backyard.
**** Product link
https://www.homedepot.com/p/Outdoor-Essentials-19-32-in-D-x-5-1-2-in-W-x-6-ft-H-Cedar-Dog-Ear-Fence-Picket-327357/314521365
**** Materials breakdown
- 140 fence pickets, $516, $41.28 sales tax, $558 total
- 14 fence rails, $760, $60.88 sales tax, $821.88 total
- Fasteners: $60, $4.80 sales tax, $64.80 total
**** Total cost
- Total materials cost: $1,444.68
- Materials + labor: $2,244.68

*** Option 2 : Pressure treated pine
This would be cheaper that cedar, but would not have the same visual appeal.
**** Product link
https://www.homedepot.com/p/Outdoor-Essentials-5-8-in-x-5-1-2-in-x-6-ft-Pressure-Treated-Pine-Dog-Ear-Fence-Picket-102560/202319053
**** Materials breakdown
- 14 fence rails: $108, $8.64 sales tax, $116.64 total
- 140 fence pickets, $315, $25.20 sales tax, $340.20 total
- Fasteners: $60, $4.80 sales tax, $64.80 total
**** Total cost
- Total materials cost: $521.64
- Materials + labor: $1,321.68
